language: python
python:
  - "3.3"
  - "2.7"
before_install:
	- "export DISPLAY=:99.0"
	- "sh -e /etc/init.d/xvfb start"
install: pip install -r requirements.txt
# command to run tests, e.g. python setup.py test
script:  nosetests